### ISSUE TITLE
Exception adding Strike indexer - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by kibble1** [zone117x/Jackett#143]
in v.0.6.2.0
getting exception while trying to add Strike Search indexer - error log below:

2015-08-20 13:04:24.2443 Error Top level exception System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Services.ServiceConfigService.RemoveService() in C:\Git\Jackett\src\Jackett\Services\ServiceConfigService.cs:line 122
   at Jackett.Services.ServiceConfigService.Uninstall() in C:\Git\Jackett\src\Jackett\Services\ServiceConfigService.cs:line 108
   at JackettConsole.Program.Main(String[] args) in C:\Git\Jackett\src\Jackett.Console\Program.cs:line 101
2015-08-20 13:04:27.7911 Info Service starting 
2015-08-20 13:04:27.9630 Info Starting Jackett 0.6.2.0 
2015-08-20 13:04:27.9630 Info Using HTTP Client: HttpWebClient 
2015-08-20 13:04:28.7286 Info Starting web server at http://127.0.0.1:9117/ 
2015-08-20 13:04:28.8693 Info Service started 
2015-08-20 13:04:59.0725 Error Error on 20150820130459 for Strike.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Indexers.Strike.<PerformQuery>d__14.MoveNext() in C:\Git\Jackett\src\Jackett\Indexers\Strike.cs:line 84

{"statuscode":404,"message":"Please enter a phrease."} 
2015-08-20 13:04:59.0725 Error Exception in Configure System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Indexers.BaseIndexer.OnParseError(String results, Exception ex) in C:\Git\Jackett\src\Jackett\Indexers\BaseIndexer.cs:line 130
   at Jackett.Indexers.Strike.<PerformQuery>d__14.MoveNext() in C:\Git\Jackett\src\Jackett\Indexers\Strike.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.Strike.<ApplyConfiguration>d__12.MoveNext() in C:\Git\Jackett\src\Jackett\Indexers\Strike.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Configure>d__15.MoveNext() in C:\Git\Jackett\src\Jackett\Controllers\AdminController.cs:line 183

**Comment by Kayomani** [comment]
Strike seems to require a search term so its not going to work for RSS, I am going to guess they did not previously require a search term?

It might be something to do with their site, I see they have stopped posting updates on their twitter https://twitter.com/strikesearch

**Comment by zone117x** [comment]
Fixed in develop branch
