### ISSUE TITLE
Error adding ThePirateBay

### ISSUE THREAD

**Issue by kibble1** [zone117x/Jackett#144]
v06.2.0
getting an error adding The Pirate Bay - error log below:

2015-08-20 13:08:19.5616 Error On attempt 1 checking for results from The Pirate Bay: An error occurred while sending the request. 
2015-08-20 13:08:20.2022 Error On attempt 2 checking for results from The Pirate Bay: An error occurred while sending the request. 
2015-08-20 13:08:20.8272 Error On attempt 3 checking for results from The Pirate Bay: An error occurred while sending the request. 
2015-08-20 13:08:21.3585 Error Exception in Configure System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Jackett.Indexers.BaseIndexer.<RequestStringWithCookiesAndRetry>d__52.MoveNext() in C:\Git\Jackett\src\Jackett\Indexers\BaseIndexer.cs:line 282
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Indexers.ThePirateBay.<PerformQuery>d__12.MoveNext() in C:\Git\Jackett\src\Jackett\Indexers\ThePirateBay.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.ThePirateBay.<ApplyConfiguration>d__10.MoveNext() in C:\Git\Jackett\src\Jackett\Indexers\ThePirateBay.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Configure>d__15.MoveNext() in C:\Git\Jackett\src\Jackett\Controllers\AdminController.cs:line 183

**Comment by zone117x** [comment]
Dupe https://github.com/zone117x/Jackett/issues/142

**Comment by kibble1** [comment]
Not a dupe PD still doesn't work in v0.6.3.0

**Comment by Kayomani** [comment]
I have just tested it and there is nothing wrong with it which means its a config issue on your system.  

It looks like its having an issue creating the SSL connection.  Are you using linux with the ssl fix?

**Comment by kibble1** [comment]
no, running it on Windows Server 2012 R2

just tried it again and got the error below after changing the url to https://thepiratebay.se/


2015-08-26 17:40:43.9327 Error Exception in Configure System.Exception: Could not find releases from this URL
   at Jackett.Indexers.ThePirateBay.<>c.<ApplyConfiguration>b__12_0() in C:\Git\Jackett\src\Jackett\Indexers\ThePirateBay.cs:line 61
   at Jackett.Indexers.BaseIndexer.<ConfigureIfOK>d__57.MoveNext() in C:\Git\Jackett\src\Jackett\Indexers\BaseIndexer.cs:line 366
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.ThePirateBay.<ApplyConfiguration>d__12.MoveNext() in C:\Git\Jackett\src\Jackett\Indexers\ThePirateBay.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Configure>d__15.MoveNext() in C:\Git\Jackett\src\Jackett\Controllers\AdminController.cs:line 185

**Comment by kibble1** [comment]
forgot to add that since Strike is working I only use PB as a backup.

Strike pretty well makes having all the other indexers redundant IMO
