### ISSUE TITLE
[REQ] shazbat

### ISSUE THREAD

**Issue by CKanKan** [zone117x/Jackett#151]
is it possible for you to add support for shazbat.tv ?

**Comment by Kayomani** [comment]
The only details I can find for is its a new tracker that is in beta, do you have any invites so I can take a look?

**Comment by CKanKan** [comment]
unfortunately I already used the invite I had. It seems to be a very basic Feed like TvTorrents was.

**Comment by CKanKan** [comment]
I now have an invite how do i get this to you?

**Comment by Kayomani** [comment]
I'll be able to sort this next week, will drop you a message later in the week as i am afk.

**Comment by Kayomani** [comment]
Send it to my name at gmail dot com please

**Comment by CKanKan** [comment]
Sent

**Comment by Kayomani** [comment]
The rss feed doesn't include size info so I'll write a scraper which will also allow for search in a couple of days.

Nice to see a site using web sockets, fortunately its not a requirement ;D

**Comment by CKanKan** [comment]
Thank you I appreciate it.

**Comment by Kayomani** [comment]
I have finished work on this and it will be in the next release.

Its mostly just working from their rss feed which is missing peer information.  I have done search too but a) their search does not do a very good job and b) it seems to just log you out after a day but that just seems to be an issue with the site in general so I can't really recommend you use the search currently.

**Comment by CKanKan** [comment]
I am unable to get this to work. it looks like Sonnar is rejecting it because it returns no size. is there a way to force a size? 

generic error
Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.

Message
An error occurred while processing feed item from http://***.*.*.*:9117/torznab/shazbat/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<removed>&offset=0&limit=100: Unable to parse size from: The.Mindy.Project.S04E03.720p.WEBRip.h264-MileyCyrus.mkv

Exception
NzbDrone.Core.Indexers.Exceptions.SizeParsingException: Unable to parse size from: The.Mindy.Project.S04E03.720p.WEBRip.h264-MileyCyrus.mkv
   at NzbDrone.Core.Indexers.RssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 134
   at NzbDrone.Core.Indexers.TorrentRssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRssParser.cs:line 38
   at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 41
   at NzbDrone.Core.Indexers.RssParser.ProcessItem(XElement item) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 112
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 48
