### ISSUE TITLE
shazbat not working with Sonarr

### ISSUE THREAD

**Issue by CKanKan** [zone117x/Jackett#208]
I am unable to get this to work. it looks like Sonnar is rejecting it because it returns no size. is there a way to force a size?

generic error
Invalid request Validation failed: 
-- No results were returned from your indexer, please check your settings.

Message
An error occurred while processing feed item from http://**...:9117/torznab/shazbat/api?t=tvsearch&cat=5030,5040&extended=1&apikey=&offset=0&limit=100: Unable to parse size from: The.Mindy.Project.S04E03.720p.WEBRip.h264-MileyCyrus.mkv

Exception
NzbDrone.Core.Indexers.Exceptions.SizeParsingException: Unable to parse size from: The.Mindy.Project.S04E03.720p.WEBRip.h264-MileyCyrus.mkv
at NzbDrone.Core.Indexers.RssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 134
at NzbDrone.Core.Indexers.TorrentRssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRssParser.cs:line 38
at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 41
at NzbDrone.Core.Indexers.RssParser.ProcessItem(XElement item) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 112
at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 48

**Comment by Kayomani** [comment]
Fixed
