### ISSUE TITLE
GetStrike not working

### ISSUE THREAD

**Issue by tmas** [zone117x/Jackett#22]
I'm able to connect to the api for other trackers (I tested using thepiratebay) but when I set up Strike I get an error from Sonarr. The dialog says "Unable to connect to indexer, check the log for more details." The log shows the following exception:

    System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
       at System.Xml.XmlTextReaderImpl.Throw(Exception e)
       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
       at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
       at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
       at System.Xml.XmlTextReaderImpl.Read()
       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
       at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
       at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess(IndexerResponse indexerResponse) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 16
       at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 40
       at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 197
       at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 211

After taking a quick look at the code, it looks to me like the the Strike.cs file may have simply been omitted from the github commit that implemented it. Should be a quick fix if someone has that locally.

**Comment by zone117x** [comment]
You were right, Strike.cs file was missing. Fixed in latest release. Thanks
