### ISSUE TITLE
AlphaRatio

### ISSUE THREAD

**Issue by jtscott** [zone117x/Jackett#57]
Hi - Getting this error on AlphaRatio today.

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.<ProcessHttpRequest>d__8.MoveNext() in c:\Users\Matthew\Source\Repos\Jackett\src\Jackett\Server.cs:line 135 
 System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

**Comment by zone117x** [comment]
This appears to have been a bug with AlphaRatio. I've just tested now and am not getting this problem.
